-- Create Profiles table (extends Auth Users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  rank int default 0,
  exp int default 0,
  stones int default 0,
  sect_id int default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Create Policy: Public can view profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

-- Create Policy: Users can update own profile
create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create Policy: Users can insert their own profile
create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url, rank, exp, stones, sect_id)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url', 0, 0, 100, 1);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create Inventory Table
create table public.inventory (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  item_id int not null,
  quantity int default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.inventory enable row level security;

create policy "Users can view own inventory."
  on inventory for select
  using ( auth.uid() = user_id );

create policy "Users can update own inventory."
  on inventory for all
  using ( auth.uid() = user_id );

-- Create Movies table
create table public.movies (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  cover_image text,
  video_url text,
  episode_count int,
  rating decimal(3,1),
  views bigint default 0,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.movies enable row level security;

create policy "Movies are viewable by everyone."
  on movies for select
  using ( true );

-- Create Reviews table
create table public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  movie_id bigint references public.movies(id) not null,
  rating int check (rating >= 1 and rating <= 10),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, movie_id)
);

alter table public.reviews enable row level security;

create policy "Reviews are viewable by everyone."
  on reviews for select
  using ( true );

create policy "Users can manage own reviews."
  on reviews for all
  using ( auth.uid() = user_id );

-- Create Watch History table
create table public.watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  movie_id bigint references public.movies(id) not null,
  watched_at timestamp with time zone default timezone('utc'::text, now()) not null,
  progress_seconds int default 0
);

alter table public.watch_history enable row level security;

create policy "Users can view own watch history."
  on watch_history for select
  using ( auth.uid() = user_id );

create policy "Users can update own watch history."
  on watch_history for all
  using ( auth.uid() = user_id );

-- Create Playlists table
create table public.playlists (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  name text not null,
  description text,
  is_public boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.playlists enable row level security;

create policy "Users can view own playlists and public ones."
  on playlists for select
  using ( auth.uid() = user_id or is_public );

create policy "Users can manage own playlists."
  on playlists for all
  using ( auth.uid() = user_id );

-- Create Playlist Items table
create table public.playlist_items (
  id bigint generated by default as identity primary key,
  playlist_id bigint references public.playlists(id) not null,
  movie_id bigint references public.movies(id) not null,
  order_index int default 0,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.playlist_items enable row level security;

create policy "Playlist items viewable based on playlist access."
  on playlist_items for select
  using ( exists (
    select 1 from playlists p
    where p.id = playlist_id
    and (p.is_public or p.user_id = auth.uid())
  ) );

create policy "Users can manage items in own playlists."
  on playlist_items for all
  using ( exists (
    select 1 from playlists p
    where p.id = playlist_id and p.user_id = auth.uid()
  ) );

-- Create Notifications table
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  title text not null,
  content text,
  type text, -- 'update', 'recommendation', etc.
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.notifications enable row level security;

create policy "Users can view own notifications."
  on notifications for select
  using ( auth.uid() = user_id );

create policy "Users can update own notifications."
  on notifications for update
  using ( auth.uid() = user_id );

-- Create Comments table for movie discussions
create table public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  movie_id bigint references public.movies(id) not null,
  parent_comment_id bigint references public.comments(id),
  content text not null,
  likes int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.comments enable row level security;

create policy "Comments are viewable by everyone."
  on comments for select
  using ( true );

create policy "Users can manage own comments."
  on comments for all
  using ( auth.uid() = user_id );
